dependencyManagement {
    imports {
        mavenBom "org.hyperledger.besu:bom:${besuVersion}"
        // remove temp ref to local build of besu with safe BesuVersionUtils
        // mavenBom "org.hyperledger.besu:bom:25.10-develop-d28fd4f"
        // Removed log4j-bom, using logback instead
        mavenBom "org.apache.logging.log4j:log4j-bom:2.24.3"
    }
}

configurations.all {
    exclude group: 'org.apache.logging.log4j', module: 'log4j-slf4j2-impl'
    exclude group: 'org.apache.logging.log4j', module: 'log4j-core'
    exclude group: 'org.apache.logging.log4j', module: 'log4j-api'
}

dependencies {
    implementation 'io.consensys.tuweni:tuweni-bytes'
    implementation 'io.consensys.tuweni:tuweni-units'
    implementation 'org.bouncycastle:bcprov-jdk18on'

    // Use Logback as SLF4J implementation instead of Log4j2
    implementation 'ch.qos.logback:logback-classic:1.4.14'
    implementation 'org.hyperledger.besu:gnark:1.4.1-GRAAL:static@jar'
    implementation 'org.hyperledger.besu:secp256k1:1.4.1-GRAAL:static@jar'
    implementation 'org.hyperledger.besu:boringssl:1.4.1-GRAAL:static@jar'
    implementation 'org.graalvm.sdk:graal-sdk:24.0.2'

    // Exclude JNA-based native libraries from besu-crypto-services since they are not useful
    // for GraalVM native compilation. We use the static variants instead.
    implementation('org.hyperledger.besu.internal:besu-crypto-services') {
        exclude group: 'org.hyperledger.besu', module: 'gnark'
        exclude group: 'org.hyperledger.besu', module: 'secp256k1'
        exclude group: 'org.hyperledger.besu', module: 'boringssl'
    }

}
